const data = [
    
    {'tittle':"Take a break",
    'des':"This website which use help taking break while using laptop or desktop for longtime",
    'tech1':"Html5",
    'tech2':"CSS3",
    'tech3':"JavaScript",
    'link' :"",
},

{'tittle':"Whats App portfolio",
    'des':"This website which can send you my resume on basis of questions in chat.",
    'tech1':"Html5",
    'tech2':"CSS3",
    'tech3':"JavaScript",
    'link' :"",
},
{'tittle':"Chat App",
    'des':"App in which two more persons can talk together and can send audio and photos.",
    'tech1':"React",
    'tech2':"firebase",
    'tech3':"SCSS",
},
{'tittle':"30Days JavaScript",
    'des':"It is github Repo , of me taking Challenge to code javascript small project for 30days.",
    'tech1':"Html5",
    'tech2':"CSS3",
    'tech3':"JavaScript",
    'link' :"",
},
{'tittle':"Resume Creator",
    'des':"web page in which user fill details in resume templates and can download that resume.",
    'tech1':"Html5",
    'tech2':"CSS3",
    'tech3':"JavaScript",
    'link' :"",
},
{'tittle':"Attendence Tracker",
    'des':"Website where teacher collect Students attendance, send warning to the less attendence student.",
    'tech1':"Html5",
    'tech2':"CSS3",
    'tech3':"JavaScript",
    'link' :"",

},
];


export default data;