// import Head from 'next/head'


// import classNames from 'classnames'
import Hero from './hero'
import Contact from './contact'
import Layout from '../components/layout'




export default function Home() {
  // const classes = classNames(styles.container, 'my-class', { 'active-class': true });

  return (
    <Layout>
      <Hero />
      
    </Layout>
    // <>
    //   <Head>
    //     <title>Jyoti Km</title>
    //    <meta name="description" content="Generated by create next app" /> 
    //     <meta name="viewport" content="width=device-width, initial-scale=1" />
    //     <link rel="icon" href="/J.ico" />
       

    //   </Head>
    //   <main>
    //   <Layout>
    //   <Hero />
    //   <Contact />
    //   </Layout>
      
    //   </main>
    // </>
  );
}
