import Head from 'next/head'
import styles from '../styles/Pages/home.module.scss'
// import { Inter , Fira_Code } from '@next/font/google'

import classNames from 'classnames'



// const inter = Inter();
// const firaCode = Fira_Code(
//   {
//     subsets: ['light' , 'regular'],
//     weight: ['300' , '400'],
//   }
// );

export default function Home() {
  const classes = classNames(styles.container, 'my-class', { 'active-class': true });

  return (
    <>
      <Head>
        <title>Jyoti Km</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/J.ico" />
       

      </Head>
      <main>
      
      </main>
    </>
  )
}
